context:
  version: 2.4.0

package:
  name: auto-changelog
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/auto-changelog/-/auto-changelog-${{ version }}.tgz
  sha256: a58a91778cceb87e1b4d9675a869aa72d22393de273efe810f8373888e81ba9b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - auto-changelog --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Command line tool for generating a changelog from git tags and commit history
  homepage: https://github.com/cookpete/auto-changelog
  repository: https://github.com/cookpete/auto-changelog

extra:
  recipe-maintainers:
    - danielnachun
