context:
  version: "2.7.0"

package:
  name: auto-changelog
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/auto-changelog/-/auto-changelog-${{ version }}.tgz
  sha256: 984595fc0043e7dec3ce68d49e8a9dbff7d5801ad3beedd3c625f6f83af9ed4d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - auto-changelog --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Command line tool for generating a changelog from git tags and commit history
  homepage: https://github.com/cookpete/auto-changelog
  repository: https://github.com/cookpete/auto-changelog

extra:
  recipe-maintainers:
    - danielnachun
