context:
  version: "2.5.1"

package:
  name: auto-changelog
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/auto-changelog/-/auto-changelog-${{ version }}.tgz
  sha256: 821c7af578daeb7e220dd62a70ed0673cfbe437e276d611e74f4b676143964d4

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - auto-changelog --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Command line tool for generating a changelog from git tags and commit history
  homepage: https://github.com/cookpete/auto-changelog
  repository: https://github.com/cookpete/auto-changelog

extra:
  recipe-maintainers:
    - danielnachun
