context:
  version: "2.6.0"

package:
  name: auto-changelog
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/auto-changelog/-/auto-changelog-${{ version }}.tgz
  sha256: ec27c5370050e5d780f033ca592ff57163444c25d2de3233aba314e53a6156ec

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - auto-changelog --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Command line tool for generating a changelog from git tags and commit history
  homepage: https://github.com/cookpete/auto-changelog
  repository: https://github.com/cookpete/auto-changelog

extra:
  recipe-maintainers:
    - danielnachun
